services:
  frontend:
    build: .
    container_name: frontend-baiao-tech
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Evita sobrescrever node_modules do container
    environment:
      - NODE_ENV=development
      - API_URL=https://baiaotech.store/api
      - FORM_LINK=https://forms.gle/ViFkUTk9aFq7LBUg9
      - COMMUNITY_API_URL=https://baiao-tech.github.io/communities/public/comunities.json