services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: https://0.0.0.0:8000/api/v1
        NEXT_PUBLIC_FORM_LINK: https://forms.gle/ViFkUTk9aFq7LBUg9
        NEXT_PUBLIC_COMMUNITY_API_URL: http://0.0.0.0:8000/api/v1/comunidades/
    container_name: frontend-baiao-tech
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    # sem command: deixa usar o server.js do standalone
