export const nextEvents = [
    {
        id: 1,
        title: 'FrontEnd',
        description: 'Evento de FrontEnd',
        date: 'JAN 18',
        location: 'UniCristus - Fortaleza, CE',
    },
    {
        id: 2,
        title: 'BackEnd',
        description: 'Evento de BackEnd',
        date: 'FEV 03',
        location: 'Digital College - Fortaleza, CE',
    },
    {
        id: 3,
        title: 'FullStack',
        description: 'Evento de FullStack',
        date: 'FEV 15',
        location: 'Infinity School - Fortaleza, CE',
    },
    {
        id: 4,
        title: 'DevOps',
        description: 'Evento de DevOps',
        date: 'MAR 02',
        location: 'UniCristus - Fortaleza, CE',
    },
    {
        id: 5,
        title: 'Mobile',
        description: 'Evento de Mobile',
        date: 'MAR 23',
        location: 'Digital College - Fortaleza, CE',
    },
    {
        id: 6,
        title: 'UI/UX',
        description: 'Evento de UI/UX',
        date: 'ABR 05',
        location: 'Infinity School - Fortaleza, CE',
    },
    {
        id: 7,
        title: 'IA',
        description: 'Evento de Inteligência Artificial',
        date: 'MAI 16 > MAI 18',
        location: 'Centro de Eventos - Fortaleza, CE',
    },
    {
        id: 8,
        title: 'Data Science',
        description: 'Evento de Data Science',
        date: 'AGO 05',
        location: 'UniCristus - Fortaleza, CE',
    },
    {
        id: 9,
        title: 'Cloud',
        description: 'Evento de Cloud',
        date: 'SET 16',
        location: 'UniCristus - Fortaleza, CE',
    },
    {
        id: 10,
        title: 'Blockchain',
        description: 'Evento de Blockchain',
        date: 'OCT 03',
        location: 'UniCristus - Fortaleza, CE',
    },
    {
        id: 11,
        title: 'IoT',
        description: 'Evento de IoT',
        date: 'NOV 28',
        location: 'UniCristus - Fortaleza, CE',
    },
];